apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: us-central1-docker.pkg.dev/kubernativesmain/container1/image1
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: persistent-storage
              mountPath: /shubh_PV_dir
        - name: container2
          image: us-central1-docker.pkg.dev/kubernativesmain/container2/image1
          ports:
            - containerPort: 7000
          volumeMounts:
            - name: persistent-storage
              mountPath: /shubh_PV_dir
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: pv-claim
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
